github.com:
    git_protocol: https
    users:
        neekonsu:
            oauth_token: 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
    user: neekonsu
    oauth_token: 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
